[project]
name = "screentunnel"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.5.2",
    "fastapi[standard]>=0.134.0",
    "faster-whisper>=1.2.1",
    "pillow>=12.1.1",
    "pix2text>=1.1.6",
]
